"""Neo4j schema owned by the Context Graph bounded module."""

CONTEXT_GRAPH_SCHEMA = (
    "CREATE CONSTRAINT cg_case_id IF NOT EXISTS FOR (n:CGCase) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_agent_run_id IF NOT EXISTS FOR (n:CGAgentRun) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_tool_call_id IF NOT EXISTS FOR (n:CGToolCall) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_observation_id IF NOT EXISTS FOR (n:CGObservation) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_episode_id IF NOT EXISTS FOR (n:CGEpisode) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_manifest_id IF NOT EXISTS FOR (n:CGContextManifest) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_decision_id IF NOT EXISTS FOR (n:CGDecision) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_option_id IF NOT EXISTS FOR (n:CGOption) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_policy_version_id IF NOT EXISTS FOR (n:CGPolicyVersion) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_policy_evaluation_id IF NOT EXISTS FOR (n:CGPolicyEvaluation) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE INDEX cg_case_tenant IF NOT EXISTS FOR (n:CGCase) ON (n.tenant)",
    "CREATE INDEX cg_manifest_tenant IF NOT EXISTS FOR (n:CGContextManifest) ON (n.tenant)",
    "CREATE INDEX cg_decision_tenant IF NOT EXISTS FOR (n:CGDecision) ON (n.tenant)",
    "CREATE CONSTRAINT cg_approval_id IF NOT EXISTS FOR (n:CGApproval) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_exception_id IF NOT EXISTS FOR (n:CGExceptionGrant) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_correction_id IF NOT EXISTS FOR (n:CGCorrection) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_action_id IF NOT EXISTS FOR (n:CGAction) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_outcome_id IF NOT EXISTS FOR (n:CGOutcome) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_feedback_id IF NOT EXISTS FOR (n:CGFeedback) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE CONSTRAINT cg_redaction_id IF NOT EXISTS FOR (n:CGRedaction) REQUIRE (n.tenant, n.id) IS UNIQUE",
    "CREATE INDEX cg_approval_expiry IF NOT EXISTS FOR (n:CGApproval) ON (n.tenant, n.expires_at)",
    "CREATE INDEX cg_exception_expiry IF NOT EXISTS FOR (n:CGExceptionGrant) ON (n.tenant, n.expires_at)",
    "CREATE INDEX cg_decision_created IF NOT EXISTS FOR (n:CGDecision) ON (n.tenant, n.created_at)",
    "CREATE INDEX cg_episode_session IF NOT EXISTS FOR (n:CGEpisode) ON (n.tenant, n.session_id, n.sequence)",
)
