'use strict';

const fs = require('fs');
const path = require('path');

const sourceFiles = {
  '/quiz.html': ['quiz.html', 'text/html; charset=utf-8'],
  '/questions.js': ['questions.js', 'application/javascript; charset=utf-8'],
  '/config.js': ['config.js', 'application/javascript; charset=utf-8'],
  '/auth.js': ['auth.js', 'application/javascript; charset=utf-8'],
  '/tracker.js': ['tracker.js', 'application/javascript; charset=utf-8'],
};

const assets = Object.fromEntries(Object.entries(sourceFiles).map(([url, [file, contentType]]) => [
  url,
  { body: fs.readFileSync(path.join(__dirname, file), 'utf8'), contentType },
]));

const worker = `// Generated by build-site.js — do not edit directly.\nconst ASSETS = ${JSON.stringify(assets)};\n\nexport default {\n  async fetch(request) {\n    const url = new URL(request.url);\n    const asset = ASSETS[url.pathname === '/' ? '/quiz.html' : url.pathname];\n    if (!asset) return new Response('Not found', { status: 404 });\n    return new Response(asset.body, { headers: { 'content-type': asset.contentType, 'cache-control': 'no-store' } });\n  },\n};\n`;

const output = path.join(__dirname, 'dist', 'server');
fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(path.join(output, 'index.js'), worker, 'utf8');
fs.writeFileSync(path.join(output, 'package.json'), '{"type":"module"}\n', 'utf8');
console.log('Built Cloudflare Worker bundle.');
