'use strict';

const fs = require('fs');
const path = require('path');

const sourceFiles = {
  '/quiz.html': ['quiz.html', 'text/html; charset=utf-8'],
  '/questions.js': ['questions.js', 'application/javascript; charset=utf-8'],
  '/config.js': ['config.js', 'application/javascript; charset=utf-8'],
  '/auth.js': ['auth.js', 'application/javascript; charset=utf-8'],
  '/tracker.js': ['tracker.js', 'application/javascript; charset=utf-8'],
  '/1samuel-test.html': ['1samuel-test.html', 'text/html; charset=utf-8'],
  '/data/1samuel-1-2.js': ['data/1samuel-1-2.js', 'application/javascript; charset=utf-8'],
  '/test-tracker.js': ['test-tracker.js', 'application/javascript; charset=utf-8'],
  '/manifest.webmanifest': ['manifest.webmanifest', 'application/manifest+json; charset=utf-8'],
  '/service-worker.js': ['service-worker.js', 'application/javascript; charset=utf-8'],
  '/icon-192.png': ['icon-192.png', 'image/png'],
  '/icon-512.png': ['icon-512.png', 'image/png'],
};

const assets = Object.fromEntries(Object.entries(sourceFiles).map(([url, [file, contentType]]) => {
  const binary = contentType.startsWith('image/');
  return [url, {
    body: fs.readFileSync(path.join(__dirname, file), binary ? 'base64' : 'utf8'),
    contentType,
    encoding: binary ? 'base64' : 'text',
  }];
}));

const worker = `// Generated by build-site.js — do not edit directly.\nconst ASSETS = ${JSON.stringify(assets)};\n\nexport default {\n  async fetch(request) {\n    const url = new URL(request.url);\n    const asset = ASSETS[url.pathname === '/' ? '/quiz.html' : url.pathname];\n    if (!asset) return new Response('Not found', { status: 404 });\n    const body = asset.encoding === 'base64' ? Uint8Array.from(atob(asset.body), c => c.charCodeAt(0)) : asset.body;\n    return new Response(body, { headers: { 'content-type': asset.contentType, 'cache-control': 'no-store' } });\n  },\n};\n`;

const output = path.join(__dirname, 'dist', 'server');
fs.mkdirSync(output, { recursive: true });
fs.writeFileSync(path.join(output, 'index.js'), worker, 'utf8');
fs.writeFileSync(path.join(output, 'package.json'), '{"type":"module"}\n', 'utf8');
console.log('Built Cloudflare Worker bundle.');
